### ISSUE TITLE
Local installation still references tiles from external URL

### ISSUE THREAD

**Issue by ngrubert** [geops/tree-app#168]
I managed to install "treeapp" on my local linux machine.
However, when opening the local installation at http://localhost:3000/, the application still tries to fetch the ".pbf" files from the exernal URL https://tiles.tree-app.ch/tree/link/to/pbf/file (e.g. https://tiles.tree-app.ch/tree/8/133/90.pbf) instead from my local machine.

**Comment by friedjoff** [comment]
Good point! I'll make the endpoint for the vector tiles configurable.
